from django.urls import path
from . import views

urlpatterns = [
     path("", views.index, name="index"),
     path("logout", views.logoutuser, name="logout"),
     path("isauthenticated", views.isauthenticated, name="isauthenticated"),
     path("loginuser", views.loginuser, name="loginuser"),
     path("register", views.register, name="register"),
     path("passwordchange", views.passwordchange, name="passwordchange"),
     path("getuserinfo", views.userinfo, name="getuserinfo"),
     path("updateuserinfo", views.updateuserinfo, name="updateuserinfo"),
     path("accountsettings", views.index, name="accountsettings"),
     path("passwordupdate", views.index, name="passwordupdate"),
     path("login", views.index, name="login"),
     path("signin", views.index, name="passwordchange"),
     path("userinfo", views.index, name="userinfo"),
     path("gettransactions/<int:idtype>", views.gettransactions, name="gettransactions"),
     path("inserttransaction", views.newtransaction, name="inserttransaction"),
     path("newincome", views.index, name="newtransaction"),
     path("newexpense", views.index, name="newtransaction"),
     path("updatetransaction", views.updatetransaction, name="updatetransaction"),
     path("deletetransaction", views.deletetransaction, name="deletetransaction"),
     path("getcategories/<int:idType>", views.getcategories, name="getcategories"),
     path("getscheduletypes", views.getscheduletypes, name="getscheduletypes"),
     path("expenses", views.index, name="expenses"),
     path("expenses/dow", views.index, name="dowexpenses"),
     path("expenses/om", views.index, name="omexpenses"),
     path("expenses/oy", views.index, name="oyexpenses"),
     path("expenses/u", views.index, name="uexpenses"),
     path("expenses/r", views.index, name="rexpenses"),
     path("expenses", views.index, name="expenses"),
     path("income/dow", views.index, name="dowincome"),
     path("income/om", views.index, name="omincome"),
     path("income/oy", views.index, name="oyincome"),
     path("income/u", views.index, name="uincome"),
     path("income/r", views.index, name="rincome"),
     path("closetransaction", views.closetransaction, name="closetransaction"),
     path("deletedayweek", views.dayweekaddremove, name="deletedayweek"),
     path("getdaysweek", views.getdaysweek, name="getdaysweek"),
     path("updatedayofmonth", views.updatedayofmonth, name="updatedayofmonth"),
     path("updatedayofyear", views.updatedayofyear, name="updatedayofyear"),
     path("updateuniquedate", views.updateuniquedate, name="updateuniquedate"),
     path("updaterangedates", views.updaterangedates, name="updaterangedates"),
     path("getfilteredtrans", views.getfilteredtrans, name="getfilteredtrans"),
     path("getjoineddate", views.getdatejoined, name="getdatejoined")
 ]