# Generated by Django 4.1 on 2022-08-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familybudget', '0003_remove_transaction_type_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='TransactionCategory',
        ),
        migrations.RenameModel(
            old_name='Type',
            new_name='TransactionType',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='duedate',
        ),
        migrations.AddField(
            model_name='transaction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('dayofmonth', models.IntegerField(default=None)),
                ('dayofyear', models.IntegerField(default=None)),
                ('rangef', models.DateField(default=None)),
                ('ranget', models.DateField(default=None)),
                ('start', models.DateField(default=None)),
                ('end', models.DateField(default=None)),
                ('daysweek', models.ManyToManyField(default=None, related_name='schedules', to='familybudget.dayweek')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='familybudget.scheduletype')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='familybudget.schedule'),
        ),
    ]
