# Generated by Django 4.1 on 2022-08-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familybudget', '0004_dayweek_scheduletype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletype',
            name='type',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduletype',
            name='description',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
