# Generated by Django 4.1 on 2022-08-29 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familybudget', '0006_alter_schedule_date_alter_schedule_dayofmonth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=None)),
                ('month', models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dayofyear',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='familybudget.dayyear'),
        ),
    ]
