# Generated by Django 4.1 on 2022-08-29 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familybudget', '0007_dayyear_alter_schedule_dayofyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='dayofyear',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='familybudget.dayyear'),
        ),
    ]
