# Generated by Django 4.1 on 2022-09-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familybudget', '0008_alter_schedule_dayofyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='familybudget.transaction'),
        ),
    ]
